"""add blog topic

Revision ID: 4c1b181e470b
Revises: 68c0cb0df7a1
Create Date: 2020-05-11 11:39:40.665914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c1b181e470b'
down_revision = '68c0cb0df7a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('topic', sa.String(), nullable=True))
    op.drop_column('posts', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('posts', 'topic')
    # ### end Alembic commands ###
